Repository MonolithProjects/ansible-github_actions_runner, pull requests merged in 2023-10, with the labels that each got.

#173 chore: fix ansible-lint 6.17.2
  .ansible-lint
  .github/workflows/lint.yml
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  molecule/custom_env/cleanup.yml
  molecule/custom_env/converge.yml
  molecule/custom_env/requirements.yml
  molecule/custom_env/verify.yml
  molecule/default/cleanup.yml
  molecule/default/converge.yml
  molecule/default/requirements.yml
  molecule/default/verify.yml
  molecule/org/cleanup.yml
  molecule/org/converge.yml
  molecule/org/requirements.yml
  molecule/org/verify.yml
  molecule/repo/cleanup.yml
  molecule/repo/converge.yml
  molecule/repo/requirements.yml
  molecule/repo/verify.yml
  tasks/collect_info.yml
  tasks/install_runner.yml
  tasks/uninstall_runner.yml
Labels: ci, chore

#181 fix: add become to become_user
  README.md
  tasks/install_runner.yml
Labels: bug, ci

#185 fix: gha
  .github/workflows/galaxy.yml
Labels: bug, ci

#186 fix: gha
  .github/workflows/galaxy.yml
Labels: ci
