Repository MonolithProjects/ansible-github_actions_runner, pull requests merged in 2024-05, with the labels that each got.

#204 feat: per_page github api parameter
  README.md
  defaults/main.yml
  tasks/collect_info.yml
Labels: enhancement

#208 Let "Replace runner" work with orgs
  tasks/install_runner.yml
Labels: bug

#210 feat(ci): parameterise out github account
  .github/workflows/tests.yml
  molecule/custom_env/cleanup.yml
  molecule/custom_env/converge.yml
  molecule/custom_env/verify.yml
  molecule/default/cleanup.yml
  molecule/default/converge.yml
  molecule/default/verify.yml
  molecule/org/cleanup.yml
  molecule/org/converge.yml
  molecule/org/verify.yml
  molecule/repo/cleanup.yml
  molecule/repo/converge.yml
  molecule/repo/verify.yml
Labels: ci

#211 Fixed custom_env molecule test
  .github/CONTRIBUTING.md
  .github/workflows/tests.yml
  README.md
  molecule/custom_env/cleanup.yml
  molecule/custom_env/converge.yml
  molecule/custom_env/verify.yml
  molecule/default/verify.yml
Labels: ci
